### ISSUE TITLE
missing bars - minimal/sparse data

### ISSUE THREAD

**Issue by rb643** [JohnCoene/globe4r#2]
First of all amazing plugin! 

Unfortunately I am struggling a little to add the bars to my plot. The example works perfectly, but when I run identical data with my own sparser set of datapoint I can't see any bars shows up. Is there some specific scaling/pre-formatting requires?

Attached is the csv file I was using as input with the following code:

```
countries <- read.csv('countrydata.csv')
create_globe() %>% 
  globe_bars(
    coords(lat, lon, altitude = value, color = value),
    data = countries
  ) %>% 
  scale_bars_altitude() %>% 
  scale_bars_color()
```

[countrydata.csv.zip](https://github.com/JohnCoene/globe4r/files/5676044/countrydata.csv.zip)

**Comment by JohnCoene** [comment]
That is odd, your code works on my machine with your dataset. If you are in RStudio could you open the visualisation in the browser and let me know if it's still not working?

![image](https://user-images.githubusercontent.com/7833796/101942305-9a796d80-3be9-11eb-8a5e-09b858b5c576.png)
